/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "v0.10.0-27-g8f39fb6c8a"
#endif /* AVUTIL_FFVERSION_H */
